apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-example-app
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-example-app
  template:
    metadata:
      labels:
        app: prometheus-example-app
    spec:
      containers:
        - name: prometheus-example-app
          image: dockerhuangyisan/prometheus-example-app:v0.5.0
          ports:
            - name: web
              containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
