apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lab
  name: prometheus-k8s-role
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "endpoints"]
    verbs: ["list", "get", "watch"]
