apiVersion: v1
kind: Service
metadata:
  name: prometheus-example-app
  namespace: lab
  labels:
    app: prometheus-example-app
spec:
  selector:
    app: prometheus-example-app
  ports:
    - port: 80
      targetPort: web
      name: metrics
